<script lang="ts">
    import type { Project } from "../global";
    import { slide, blur, fade } from "svelte/transition";
    import { onMount } from "svelte";
    import { cursorTracker } from "../cursorTracker";

    let display = false;
    export let ctr: cursorTracker;

    // Fullscreen project
    let fullscreen_project: Project | null = null;

    let projects: Project[] = [];

    // TODO: Implement in firebase
    projects.push({
        name: "The Beaver Project",
        description:
            "The Beaver Project is a game I made along with Baptiste, François and Paul for my Second Semester Project at school. It is a multiplayer FPS made on Unity and Firebase.",
        media: {
            type: "video",
            src: "https://firebasestorage.googleapis.com/v0/b/beaver-ea0ea.appspot.com/o/media%2FTrailer_FINAL.mp4?alt=media&token=bbef1129-a559-4a2d-817e-38941754f26a",
        },
        link: {
            display: "thebeaverproject.tk",
            url: "https://thebeaverproject.tk",
        },
        repo: {
            display: "github",
            url: "https://github.com/augustinbegue/thebeaverproject-game",
        },
        tags: ["game", "c#", "unity", "react", "firebase", "s2", "epita"],
        dates: ["01/01/2021", "06/31/2021"],
        status: "completed",
    });

    projects.push({
        name: "Wager",
        description:
            "Football prediction game built with NodeJs, Angular and Bulma. Built as a PWA, powered by a Rest API, using the football-data api and some web scraping to get its live data. The app is fully responsive and works on mobile and desktop. I've abandonned this project because it started to take a lot of my free time since I was alone on it. I may be restarting it in the future.",
        media: {
            type: "image",
            src: "https://i.ibb.co/JKd4W47/mobile-screen.png",
        },
        link: {
            display: "wager.ga",
            url: "#",
        },
        tags: [
            "game",
            "football",
            "webapp",
            "angular",
            "pwa",
            "nodejs",
            "rest",
            "scraping",
        ],
        dates: ["02/10/2019", "14/05/2021"],
        status: "abandoned",
    });

    projects.push({
        name: "Sudoku OCR",
        description:
            "This project was made during my Third Semester at school. The subject instructed us to build a program written in C able to process an image of a Sudoku in order to extract the digits contained in it and solve it.",
        media: {
            type: "image",
            src: "https://i.ibb.co/nQQd4Wy/mstsc-zcf15-R4-DIR.png",
        },
        repo: {
            display: "github",
            url: "https://github.com/augustinbegue/sudoku-ocr",
        },
        tags: ["ocr", "sudoku", "c", "image processing", "ai", "s3", "epita"],
        dates: ["09/07/2021", "12/7/2021"],
        status: "completed",
    });

    projects.push({
        name: "GPX Visualizer",
        description:
            "As a cycling enthusiast, I wanted a modern and easy way to have a live look at the files generated by my recording devices when I go out on a big ride. I therefore created a live visualizer allowing me to see a real-time replay of my rides, using a custom gpx parser (this is XML data afterall) and leafletjs for the map.",
        media: {
            type: "image",
            src: "https://s10.gifyu.com/images/MHxBO8n05h.gif",
        },
        link: {
            display: "gpx-visualizer",
            url: "https://augustinbegue.github.io/gpx-visualizer/",
        },
        repo: {
            display: "github",
            url: "https://github.com/augustinbegue/gpx-visualizer",
        },
        tags: ["webapp", "gpx", "leaflet.js", "cycling"],
        dates: ["08/01/2020", "08/24/2020"],
        status: "completed",
    });

    projects.push({
        name: "iCue Ambilight",
        description:
            "This is a windows software made with electron to allow iCue compatible Corsair devices to sync their led's color to the screen of your computer.",
        // TODO: make media a demo video
        media: {
            type: "image",
            src: "https://i.imgur.com/FrM8cjn.png",
        },
        link: {
            display: "demo",
            url: "https://youtu.be/KBrnEDs2tdk?t=36",
        },
        repo: {
            display: "github",
            url: "https://github.com/augustinbegue/icue-ambilight",
        },
        tags: ["windows", "electron", "corsair", "ambilight"],
        dates: ["12/07/2019", "..."],
        status: "inactive",
    });

    let delay = projects.length * 150;

    export function intro() {
        return new Promise<void>((resolve) => {
            display = true;
            setTimeout(() => {
                resolve();
            }, delay);
        });
    }

    export function outro() {
        return new Promise<void>((resolve) => {
            display = false;
            setFullScreenProject(null);

            setTimeout(() => {
                resolve();
            }, delay);
        });
    }

    function shuffle(arr) {
        for (let i = arr.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [arr[i], arr[j]] = [arr[j], arr[i]];
        }
    }

    onMount(() => {
        display = true;
        ctr = new cursorTracker();
    });

    function setFullScreenProject(project: Project | null) {
        fullscreen_project = project;
    }
</script>

{#if display}
    {#if fullscreen_project}
        <div
            in:blur
            out:blur
            class="w-full h-full  z-40 absolute top-0 left-0 flex items-center justify-center"
        >
            <div
                in:slide
                out:slide
                class="container max-h-full overflow-x-scroll no-scrollbar p-4 md:rounded bg-dark-300 dark:bg-dark-100 transition-all duration-300 text-white hoverable"
            >
                <div class="flex place-content-between p-4 pb-2">
                    <span class="text-xl font-bold"
                        >{fullscreen_project.name}</span
                    >
                    <button
                        class="text-xl text-button hoverable"
                        on:click={() => {
                            setFullScreenProject(null);
                        }}>x</button
                    >
                </div>
                <div
                    class="p-4 pt-2 flex flex-row flex-wrap md:flex-nowrap flex-shrink"
                >
                    {#if fullscreen_project.media.type === "video"}
                        <video
                            class="rounded md:w-1/2"
                            src={fullscreen_project.media.src}
                            controls={true}
                            autoplay={true}
                            muted={true}
                        />
                    {:else}
                        <img
                            class="rounded md:w-1/2 object-contain"
                            style="max-height: 50vh;"
                            src={fullscreen_project.media.src}
                            alt={fullscreen_project.name}
                        />
                    {/if}
                    <div class="md:pl-4 pt-4">
                        <p class="pt-0 p-2 max-w-prose">
                            {fullscreen_project.description}
                        </p>
                        <ul class="list-none list-inside font-mono p-2">
                            {#if fullscreen_project.link}
                                <li>
                                    <a
                                        class="underline hoverable"
                                        href={fullscreen_project.link.url}
                                        target="_blank"
                                        >{fullscreen_project.link.display}</a
                                    >
                                </li>
                            {/if}
                            {#if fullscreen_project.repo}
                                <li>
                                    <a
                                        class="underline hoverable"
                                        href={fullscreen_project.repo.url}
                                        target="_blank"
                                        >{fullscreen_project.repo.display}</a
                                    >
                                </li>
                            {/if}
                            <li>
                                <span
                                    class="{fullscreen_project.status ===
                                    'in progress'
                                        ? 'bg-yellow-100 hover:bg-dark-100 hover:text-yellow-100'
                                        : fullscreen_project.status ===
                                          'inactive'
                                        ? 'bg-gray-600 hover:bg-dark-100 hover:text-gray-600'
                                        : fullscreen_project.status ===
                                          'completed'
                                        ? 'bg-green-100 hover:bg-dark-100 hover:text-green-100'
                                        : 'bg-red-100 hover:bg-dark-100 hover:text-red-100'} rounded-full px-2 p-1/2 duration-500 transition-all"
                                >
                                    {fullscreen_project.status}
                                </span>
                            </li>
                            <li>
                                {fullscreen_project.dates[0]} -> {fullscreen_project
                                    .dates[1]}
                            </li>
                        </ul>
                        <div class="flex flex-row flex-wrap font-mono pt-4">
                            {#each fullscreen_project.tags as tag}
                                <span
                                    class="m-1 px-3 rounded-full bg-gradient-to-bl animation-onedark-rainbow"
                                    >{tag}</span
                                >
                            {/each}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {/if}
    <div>
        <div
            class="z-30 absolute p-4 pt-32 pb-32 overflow-y-scroll w-full h-full md:no-scrollbar"
        >
            <div class="container mx-auto">
                <div class="projects-grid">
                    {#each projects as project, id}
                        {#key project}
                            <div
                                class="{id === 0 || id === 4
                                    ? 'md:col-span-2'
                                    : ''} {id === 1
                                    ? 'md:row-span-2'
                                    : ''} {fullscreen_project
                                    ? fullscreen_project?.name === project.name
                                        ? 'dark:bg-dark-100'
                                        : 'opacity-10'
                                    : ''} m-4 bg-dark-300 dark:bg-dark-50 rounded text-white transition-all duration-300 hoverable"
                                in:slide={{ delay: 150 * id }}
                                out:slide={{
                                    delay: 150 * (projects.length - (id + 1)),
                                }}
                                on:dblclick={() => {
                                    setFullScreenProject(project);
                                }}
                                on:mouseenter={() => {
                                    ctr.displayText(
                                        project.tags.join(" ") + " ",
                                    );
                                }}
                                on:mouseleave={() => {
                                    ctr.hideText();
                                }}
                            >
                                <div
                                    class="flex place-content-between p-4 pb-2"
                                >
                                    <span class="text-lg font-medium"
                                        >{project.name}</span
                                    ><button
                                        class="text-button hoverable"
                                        on:click={() => {
                                            setFullScreenProject(project);
                                        }}
                                        on:mouseenter={() => {
                                            ctr.displayText("fullscreen ");
                                        }}
                                        on:mouseleave={() => {
                                            ctr.hideText();
                                        }}>[ ]</button
                                    >
                                </div>
                                <div class="p-4 pt-2 flex flex-row flex-wrap">
                                    {#if project.media.type === "video"}
                                        <video
                                            class="max-w-screen-sm w-full rounded"
                                            src={project.media.src}
                                            controls={true}
                                            autoplay={true}
                                            muted={true}
                                        />
                                    {:else}
                                        <img
                                            class="max-w-screen-sm w-full rounded"
                                            src={project.media.src}
                                            alt={project.name}
                                        />
                                    {/if}
                                    <div>
                                        <ul
                                            class="list-none list-inside font-mono p-2"
                                        >
                                            <li>
                                                {#if project.link}
                                                    <a
                                                        class="underline hoverable"
                                                        href={project.link.url}
                                                        target="_blank"
                                                        >{project.link
                                                            .display}</a
                                                    >
                                                {:else}
                                                    <a
                                                        class="underline hoverable"
                                                        href={project.repo.url}
                                                        target="_blank"
                                                        >{project.repo
                                                            .display}</a
                                                    >
                                                {/if}
                                            </li>
                                            <li>
                                                <span
                                                    class="{project.status ===
                                                    'in progress'
                                                        ? 'bg-yellow-100 hover:bg-dark-100 hover:text-yellow-100'
                                                        : project.status ===
                                                          'inactive'
                                                        ? 'bg-dark-400 hover:bg-dark-100 hover:text-dark-400'
                                                        : project.status ===
                                                          'completed'
                                                        ? 'bg-green-100 hover:bg-dark-100 hover:text-green-100'
                                                        : 'bg-red-100 hover:bg-dark-100 hover:text-red-100'} rounded-full px-2 p-1/2 duration-500 transition-all"
                                                >
                                                    {project.status}
                                                </span>
                                            </li>
                                            <li>
                                                {project.dates[0]} -> {project
                                                    .dates[1]}
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {/key}
                    {/each}
                </div>
            </div>
        </div>
    </div>
{/if}

<style lang="postcss">
    .projects-grid {
        @apply grid grid-flow-row grid-cols-1 md:grid-cols-3 gap-4 place-content-center;
    }
</style>
