<script lang="ts">
    import type { Project } from "../global";

    import { slide, blur } from "svelte/transition";

    let display = false;

    // Fullscreen project
    let fullscreen_project: Project | null = null;

    let projects: Project[] = [];

    // TODO: Implement in firebase
    projects.push({
        name: "The Beaver Project",
        description:
            "The Beaver Project is a game I made along with Baptiste, François and Paul for my Second Semester Project at school. It is a multiplayer FPS made on Unity and Firebase.",
        media: {
            type: "video",
            src: "https://firebasestorage.googleapis.com/v0/b/beaver-ea0ea.appspot.com/o/media%2FTrailer_FINAL.mp4?alt=media&token=bbef1129-a559-4a2d-817e-38941754f26a",
        },
        link: {
            display: "thebeaverproject.tk",
            url: "https://thebeaverproject.tk",
        },
        repo: {
            display: "github",
            url: "https://github.com/augustinbegue/thebeaverproject-game",
        },
        tags: ["game", "c#", "unity", "react", "firebase", "s2", "epita"],
        dates: ["01/01/2021", "06/31/2021"],
        status: "completed",
    });

    projects.push({
        name: "Wager",
        description:
            "Football prediction game built with NodeJs, Angular and Bulma. Built as a PWA, powered by a Rest API, using the football-data api and some web scraping to get its live data. The app is fully responsive and works on mobile and desktop. I've abandonned this project because it started to take a lot of my free time since I was alone on it. I may be restarting it in the future.",
        media: {
            type: "image",
            src: "https://i.ibb.co/JKd4W47/mobile-screen.png",
        },
        link: {
            display: "wager.ga",
            url: "#",
        },
        tags: [
            "game",
            "football",
            "webapp",
            "angular",
            "pwa",
            "nodejs",
            "rest",
            "scraping",
        ],
        dates: ["02/10/2019", "14/05/2021"],
        status: "abandoned",
    });

    projects.push({
        name: "Sudoku OCR",
        description:
            "This project was made during my Third Semester at school. The subject instructed us to build a program written in C able to process an image of a Sudoku in order to extract the digits contained in it and solve it.",
        media: {
            type: "image",
            src: "https://i.ibb.co/nQQd4Wy/mstsc-zcf15-R4-DIR.png",
        },
        repo: {
            display: "github",
            url: "https://github.com/augustinbegue/sudoku-ocr",
        },
        tags: ["ocr", "sudoku", "c", "image processing", "ai", "s3", "epita"],
        dates: ["09/07/2021", "12/7/2021"],
        status: "completed",
    });

    projects.push({
        name: "GPX Visualizer",
        description:
            "As a cycling enthusiast, I wanted a modern and easy way to have a live look at the files generated by my recording devices when I go out on a big ride. I therefore created a live visualizer allowing me to see a real-time replay of my rides, using a custom gpx parser (this is XML data afterall) and leafletjs for the map.",
        media: {
            type: "image",
            src: "https://s10.gifyu.com/images/MHxBO8n05h.gif",
        },
        link: {
            display: "gpx-visualizer",
            url: "https://augustinbegue.github.io/gpx-visualizer/",
        },
        repo: {
            display: "github",
            url: "https://github.com/augustinbegue/gpx-visualizer",
        },
        tags: ["webapp", "gpx", "leaflet.js", "cycling"],
        dates: ["08/01/2020", "08/24/2020"],
        status: "completed",
    });

    projects.push({
        name: "iCue Ambilight",
        description:
            "This is a windows software made with electron to allow iCue compatible Corsair devices to sync their led's color to the screen of your computer.",
        // TODO: make media a demo video
        media: {
            type: "image",
            src: "https://i.imgur.com/FrM8cjn.png",
        },
        link: {
            display: "demo",
            url: "https://youtu.be/KBrnEDs2tdk?t=36",
        },
        repo: {
            display: "github",
            url: "https://github.com/augustinbegue/icue-ambilight",
        },
        tags: ["windows", "electron", "corsair", "ambilight"],
        dates: ["12/07/2019", "..."],
        status: "inactive",
    });

    let delay = projects.length * 150;

    export function intro() {
        return new Promise<void>((resolve) => {
            display = true;
            setTimeout(() => {
                resolve();
            }, delay);
        });
    }

    export function outro() {
        return new Promise<void>((resolve) => {
            display = false;

            setTimeout(() => {
                resolve();
            }, delay);
        });
    }

    function setFullScreenProject(project: Project | null) {
        fullscreen_project = project;
    }
</script>

{#if fullscreen_project}
    <div
        in:blur
        out:blur
        class="w-full h-full bg-black bg-opacity-60 z-40 absolute top-0 left-0 flex items-center justify-center"
    >
        <div
            in:slide
            out:slide
            class="container rounded bg-black opacity-90 p-4 m-4 transition-all duration-300 text-white hover:opacity-100"
        >
            <div class="flex place-content-between p-4 pb-2">
                <span class="text-xl font-bold">{fullscreen_project.name}</span>
                <button
                    class="hover:font-bold text-xl"
                    on:click={() => {
                        setFullScreenProject(null);
                    }}>x</button
                >
            </div>
            <div class="p-4 pt-2 flex flex-row">
                {#if fullscreen_project.media.type === "video"}
                    <video
                        class="w-full rounded max-w-screen-lg"
                        src={fullscreen_project.media.src}
                        controls={true}
                        autoplay={true}
                        muted={true}
                    />
                {:else}
                    <img
                        class="w-full rounded max-w-screen-lg"
                        src={fullscreen_project.media.src}
                        alt={fullscreen_project.name}
                    />
                {/if}
                <div class="p-4 pt-0">
                    <p class="pt-0 p-2">{fullscreen_project.description}</p>
                    <ul class="list-none list-inside font-mono p-2">
                        {#if fullscreen_project.link}
                            <li>
                                <a
                                    class="underline hover:decoration-blue-600"
                                    href={fullscreen_project.link.url}
                                    target="_blank"
                                    >{fullscreen_project.link.display}</a
                                >
                            </li>
                        {/if}
                        {#if fullscreen_project.repo}
                            <li>
                                <a
                                    class="underline hover:decoration-blue-600"
                                    href={fullscreen_project.repo.url}
                                    target="_blank"
                                    >{fullscreen_project.repo.display}</a
                                >
                            </li>
                        {/if}
                        <li>
                            <span
                                class="{fullscreen_project.status ===
                                'in progress'
                                    ? 'bg-yellow-400 hover:bg-black hover:text-yellow-400'
                                    : fullscreen_project.status === 'inactive'
                                    ? 'bg-gray-600 hover:bg-black hover:text-gray-600'
                                    : fullscreen_project.status === 'completed'
                                    ? 'bg-green-500 hover:bg-black hover:text-green-500'
                                    : 'bg-red-500 hover:bg-black hover:text-red-500'} rounded-full px-2 p-1/2 duration-500 transition-all"
                            >
                                {fullscreen_project.status}
                            </span>
                        </li>
                        <li>
                            {fullscreen_project.dates[0]} -> {fullscreen_project
                                .dates[1]}
                        </li>
                    </ul>
                    <div class="flex flex-row flex-wrap font-mono pt-4">
                        {#each fullscreen_project.tags as tag}
                            <span
                                class="m-1 px-3 rounded-full bg-gradient-to-bl from-green-500 to-blue-600"
                                >{tag}</span
                            >
                        {/each}
                    </div>
                </div>
            </div>
        </div>
    </div>
{/if}

{#if display}
    <div
        class="z-30 container mx-auto p-4 pt-32 pb-32 overflow-y-scroll h-full md:no-scrollbar"
    >
        <div class="projects-grid">
            {#each projects as project, id}
                {#key project}
                    <div
                        class="{id === 0 || id === 4 ? 'md:col-span-2' : ''}
                        {id === 1
                            ? 'md:row-span-2'
                            : ''} m-4 bg-black rounded text-white"
                        in:slide={{ delay: 150 * id }}
                        out:slide={{
                            delay: 150 * (projects.length - (id + 1)),
                        }}
                    >
                        <div class="flex place-content-between p-4 pb-2">
                            <span class="text-lg font-medium"
                                >{project.name}</span
                            ><button
                                class="hover:font-bold"
                                on:click={() => {
                                    setFullScreenProject(project);
                                }}>[ ]</button
                            >
                        </div>
                        <div class="p-4 pt-2 flex flex-row flex-wrap">
                            {#if project.media.type === "video"}
                                <video
                                    class="max-w-screen-sm w-full rounded"
                                    src={project.media.src}
                                    controls={true}
                                    autoplay={true}
                                    muted={true}
                                />
                            {:else}
                                <img
                                    class="max-w-screen-sm w-full rounded"
                                    src={project.media.src}
                                    alt={project.name}
                                />
                            {/if}
                            <div>
                                <ul class="list-none list-inside font-mono p-2">
                                    <li>
                                        {#if project.link}
                                            <a
                                                class="underline hover:decoration-blue-600"
                                                href={project.link.url}
                                                target="_blank"
                                                >{project.link.display}</a
                                            >
                                        {:else}
                                            <a
                                                class="underline hover:decoration-blue-600"
                                                href={project.repo.url}
                                                target="_blank"
                                                >{project.repo.display}</a
                                            >
                                        {/if}
                                    </li>
                                    <li>
                                        <span
                                            class="{project.status ===
                                            'in progress'
                                                ? 'bg-yellow-400 hover:bg-black hover:text-yellow-400'
                                                : project.status === 'inactive'
                                                ? 'bg-gray-600 hover:bg-black hover:text-gray-600'
                                                : project.status === 'completed'
                                                ? 'bg-green-500 hover:bg-black hover:text-green-500'
                                                : 'bg-red-500 hover:bg-black hover:text-red-500'} rounded-full px-2 p-1/2 duration-500 transition-all"
                                        >
                                            {project.status}
                                        </span>
                                    </li>
                                    <li>
                                        {project.dates[0]} -> {project.dates[1]}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {/key}
            {/each}
        </div>
    </div>
{/if}

<style lang="postcss">
    .projects-grid {
        @apply grid grid-flow-row grid-cols-1 md:grid-cols-3 gap-4 place-content-center;
    }
</style>
